### ISSUE TITLE
Extrair informações de conteúdo gerado dinâmicamente

### ISSUE THREAD

**Issue by thurbridi** [thurbridi/epic-games-crawler#6]

**Comment by thurbridi** [comment]
- [Scrapy-splash](https://github.com/scrapy-plugins/scrapy-splash)
- Selenium

**Comment by Thaleszh** [comment]
done in #14

**Comment by Thaleszh** [comment]
https://stackoverflow.com/questions/35352423/scrapy-shell-and-scrapy-splash
